services:
  # Override image versions
  app:
    image: beabee/beabee-legacy-app:${HIVE_VERSION}
  api_app:
    image: beabee/beabee-api-app:${HIVE_VERSION}
  webhook_app:
    image: beabee/beabee-webhook-app:${HIVE_VERSION}
  cron_app:
    image: beabee/beabee-cron-app:${HIVE_VERSION}
  migration:
    image: beabee/beabee-api-app:${HIVE_VERSION}
  run:
    image: beabee/beabee-api-app:${HIVE_VERSION}
  frontend:
    image: beabee/beabee-frontend:${HIVE_VERSION}
  app_router:
    image: beabee/beabee-router:${HIVE_VERSION}

  # Add extra services
  mail:
    image: maildev/maildev:2.1.0
    restart: unless-stopped
    labels:
      - "traefik.docker.network=traefik-ingress"
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mail.entryPoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mail.rule=Host(`mail.${BEABEE_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mail.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-mail.tls.certResolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-mail.loadbalancer.server.port=1080"
    networks:
      - internal
      - traefik-ingress

  telegram_bot:
    image: beabee/telegram-bot:latest
    volumes:
      - telegram-bot_data:/app/telegram-bot/data

    restart: unless-stopped
    environment:
      BEABEE_AUDIENCE: ${BEABEE_AUDIENCE}
      API_PROXY_URL: ${BEABEE_AUDIENCE}
      TELEGRAM_TOKEN: ${BEABEE_TELEGRAM_BOT_TOKEN}
      BEABEE_API_TOKEN: ${BEABEE_TELEGRAM_BOT_API_TOKEN}
      BEABEE_SERVICE_SECRET: ${BEABEE_SERVICE_SECRET}
      TELEGRAM_BOT_ENVIRONMENT: ${BEABEE_ENVIRONMENT}
      DEBUG: grammy*
      API_BASE_URL: /api/1.0

volumes:
  telegram-bot_data:
